services:
  mongo:
    image: mongo:5
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${PLAN_ANUAL_AUDITORIA_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${PLAN_ANUAL_AUDITORIA_PASS}
      MONGO_INITDB_DATABASE: ${PLAN_ANUAL_AUDITORIA_DB}
    ports:
      - 27017:27017
    volumes:
      - ./mongo_data:/data/db
