import * as dotenv from 'dotenv';

dotenv.config();
export const environment = {
    PLAN_ANUAL_AUDITORIA_USER:
      process.env.PLAN_ANUAL_AUDITORIA_USER,
    PLAN_ANUAL_AUDITORIA_PASS:
      process.env.PLAN_ANUAL_AUDITORIA_PASS,
    PLAN_ANUAL_AUDITORIA_HOST:
      process.env.PLAN_ANUAL_AUDITORIA_HOST,
    PLAN_ANUAL_AUDITORIA_PORT:
      process.env.PLAN_ANUAL_AUDITORIA_PORT,
    PLAN_ANUAL_AUDITORIA_DB:
      process.env.PLAN_ANUAL_AUDITORIA_DB,
    PLAN_ANUAL_AUDITORIA_HTTP_PORT:
      process.env.PLAN_ANUAL_AUDITORIA_HTTP_PORT,
    PLAN_ANUAL_AUDITORIA_AUTH_DB:
      process.env.PLAN_ANUAL_AUDITORIA_AUTH_DB,
  };